CREATE TABLE "TRIPTYCH"(

    "ID" CHARACTER VARYING(255) NOT NULL,

    "CALLING_APPLICATION" CHARACTER VARYING(255),

    "NDD" CHARACTER VARYING(255),

    "OWNING_APPLICATION" CHARACTER VARYING(255)

);
CREATE TABLE "FROZEN_STATUS"(

    "ID" CHARACTER VARYING(255) NOT NULL,

    "FROZEN" CHARACTER VARYING(255),

    "NB_FROZEN" INTEGER NOT NULL,

    "REASON_FROZEN" CHARACTER VARYING(255)

);
CREATE TABLE "FINAL_STAGE_DATE"(

    "ID" CHARACTER VARYING(255) NOT NULL,

    "DATE" TIMESTAMP,

    "NB_DOCS" INTEGER NOT NULL,

    "TRIPTYCH_ID" CHARACTER VARYING(255)

);
CREATE TABLE "FINAL_BUSINESS_PROCESSING_DATE"(

    "ID" CHARACTER VARYING(255) NOT NULL,

    "DATE" TIMESTAMP,

    "NB_DOCS" INTEGER NOT NULL,

    "FINAL_STAGE_DATE_ID" CHARACTER VARYING(255)

);
CREATE TABLE "ARCHIVING_REFERENCE_DATE"(

    "ID" CHARACTER VARYING(255) NOT NULL,

    "DATE" TIMESTAMP,

    "NB_DOCS" INTEGER NOT NULL,

    "FINAL_BUSINESS_PROCESSING_DATE_ID" CHARACTER VARYING(255),

    "FROZEN_STATUS_ID" CHARACTER VARYING(255)

);
ALTER TABLE "TRIPTYCH" ADD CONSTRAINT "CONSTRAINT_8" PRIMARY KEY("ID");
ALTER TABLE "FROZEN_STATUS" ADD CONSTRAINT "CONSTRAINT_5" PRIMARY KEY("ID");
ALTER TABLE "FINAL_STAGE_DATE" ADD CONSTRAINT "FKD2BR7VDP5MDCUD9TRLVKSIBQV" FOREIGN KEY("TRIPTYCH_ID") REFERENCES "TRIPTYCH"("ID") NOCHECK;
ALTER TABLE "FINAL_STAGE_DATE" ADD CONSTRAINT "CONSTRAINT_99" PRIMARY KEY("ID");
ALTER TABLE "FINAL_BUSINESS_PROCESSING_DATE" ADD CONSTRAINT "FK4T6WULT2JBUOLD24I1J2D003P" FOREIGN KEY("FINAL_STAGE_DATE_ID") REFERENCES "FINAL_STAGE_DATE"("ID") NOCHECK;
ALTER TABLE "FINAL_BUSINESS_PROCESSING_DATE" ADD CONSTRAINT "CONSTRAINT_9" PRIMARY KEY("ID");
ALTER TABLE "ARCHIVING_REFERENCE_DATE" ADD CONSTRAINT "FKAIAFSS042EPCQ2VBDRTQ06SJ5" FOREIGN KEY("FINAL_BUSINESS_PROCESSING_DATE_ID") REFERENCES "FINAL_BUSINESS_PROCESSING_DATE"("ID") NOCHECK;
ALTER TABLE "ARCHIVING_REFERENCE_DATE" ADD CONSTRAINT "FK7HM1L87EC2V400GQOXLHK5UHH" FOREIGN KEY("FROZEN_STATUS_ID") REFERENCES "FROZEN_STATUS"("ID") NOCHECK;
ALTER TABLE "ARCHIVING_REFERENCE_DATE" ADD CONSTRAINT "CONSTRAINT_3" PRIMARY KEY("ID");